EPAM.Web.Basics/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EPAM.Web.Basics.Models
{
    public class Product
    {

        public int Id { get; set; }

        public string Name { get; set; }

    }
}

EPAM.Web.Basics/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EPAM.Web.Basics.Models;
using Microsoft.AspNetCore.Mvc;

namespace EPAM.Web.Basics.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

EPAM.Web.Basics/Controllers/Task_8Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EPAM.Web.Basics.Models;
using Microsoft.AspNetCore.Mvc;

namespace EPAM.Web.Basics.Controllers
{
    public class Task_8Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Task8_1()
        {
            List<Product> products = new List<Product>()
            {
                new Product() {Id = 1, Name = "Азу по-татарски" },
                new Product() {Id = 2, Name = "Зразы" },
                new Product() {Id = 3, Name = "Баранья грудинка, тушенная с картофелем" },
                new Product() {Id = 4, Name = "Бефстроганов" },
                new Product() {Id = 5, Name = "Бивштекс с яйцом" }
            };

            return View(products);
        }

        public IActionResult Task8_2()
        {
            return View();
        }

        public IActionResult Task8_3()
        {
            return View();
        }

        public IActionResult Task8_4()
        {
            return View();
        }

        public IActionResult Task8_5()
        {
            return View();
        }

        public IActionResult Task8_6()
        {
            return View();
        }

        public IActionResult Task8_7()
        {
            return View();
        }

        public IActionResult Task8_8()
        {
            return View();
        }

        public IActionResult Task8_9()
        {
            return View();
        }
    }
}

EPAM.Web.Basics/Controllers/Task_9Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EPAM.Web.Basics.Controllers
{
    public class Task_9Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Task9_1()
        {
            return View();
        }

        public IActionResult Task9_2()
        {
            return View();
        }

        public IActionResult Task9_3()
        {
            return View();
        }

        public IActionResult Task9_4()
        {
            return View();
        }

        public IActionResult Task9_4_1()
        {
            return View();
        }

        public IActionResult Task9_4_2()
        {
            return View();
        }
    }
}

EPAM.Web.Basics/Views/Home/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta author="Akimov" /> 
    <title>Task 8</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
        
    </environment>
</head>
<body>
    <header>
        <div class="main-wrapper">
            <img src="~/css/pic/logo_white-blue.svg" alt="EPAM" />
        </div>
    </header>
    <h1><span>Task 8</span></h1>
    <div class="row">
        <div class="container">
            <div class="text-overlay">LIST MENU - 8.1</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_1">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">REGISTRATION FORM - 8.2</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_2">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">DROPDOWN MENU - 8.3</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_3">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">POINTING BLOCK - 8.4</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_4">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">THREE COLUMN BLOCK - 8.5</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_5">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">EQUALIZER - 8.6</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_6">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">HEADER - 8.7</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_7">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">ARTICLE - 8.8</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_8">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">STEP COUNTER - 8.9</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_8" asp-action="Task8_9">Click</a></div>
            </div>
        </div>
    </div>
    <h1><span>Task 9</span></h1>
    <div class="row">
        <div class="container">
            <div class="text-overlay">CHAR REMOVER - 9.1</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_9" asp-action="Task9_1">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">MATH CALCULATOR - 9.2</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_9" asp-action="Task9_2">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">BUTTERFLY CONTROL - 9.3</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_9" asp-action="Task9_3">Click</a></div>
            </div>
        </div>
        <div class="container">
            <div class="text-overlay">SIMPLE GALLERY - 9.4</div>
            <div class="overlay">
                <div class="text"><a asp-controller="Task_9" asp-action="Task9_4">Click</a></div>
            </div>
        </div>
    </div>

    @*<script src="~/Script/script.js"></script>*@
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_1.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Task8_1</title>
    <!--TagHelper-->
    <environment include="Development">
        <link href="~/css/Task_8/Task8_1Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div class="Menulist">
        <ul>
            @foreach (var item in Model)
            {
                <li>@item.Name</li>
            }
        </ul>
    </div>
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_2.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Task8_2</title>
    <environment include="Development">
        <link href="~/css/Task_8/Task8_2Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <form class="formMain">
        <p class="Registration">Регистрация</p>
        <p class="lineWhite"></p>
        <p>E-mail<br /><input type="text" name="name" size="15" maxlength="20" value=""></p>

        <div class="stackDiv">
            Пароль<br />
            <input type="text" name="name" size="15" maxlength="20" value="">
        </div>
        <div class="stackDiv">
            Ещё раз<br />
            <input type="text" name="name" size="15" maxlength="20" value="">
        </div>
        <button>Отправить</button>
    </form>
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_3.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DROPDOWN MENU</title>
    <environment include="Development">
        <link href="~/css/Task_8/Task8_3Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <nav>
        <ul class="topmenu">
            <li class="down"><a class="atopmenu" href=""><u>Файл</u></a>
                <ul class="submenu">
                    <li><a href="">Новый</a></li>
                    <li><a href="">Открыть</a></li>
                    <li><a href="">Сохранить</a></li>
                    <li><a href="">Закрыть</a></li>
                </ul>
            </li>
            <li class="down"><a class="atopmenu" href=""><u>Правка</u></a>
                <ul class="submenu">
                    <li><a href="">Вырезать</a></li>
                    <li><a href="">Копировать</a></li>
                    <li><a href="">Вставить</a></li>
                    <li><a href="">Удалить</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_4.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Указатель</title>
    <environment include="Development">
        <link href="~/css/Task_8/Task8_4Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div class="pointblock">Дистанции огромного размера</div>
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_5.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Хостинг</title>
    <environment include="Development">
        <link href="~/css/Task_8/Task8_5Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div class="row">
        <div class="column">
            <div class="pic1">
                <img src="~/css/Task_8/pic/Task_5img.jpg" alt="Виртуальный хостинг" />
            </div>
            <div class="label1">
                Виртуальный хостинг
            </div>
            <div class="label2">
                3.95$ в месяц
            </div>
            <button>Подробнее</button>
        </div>
        <div class="column">
            <div class="pic2">
                <img src="~/css/Task_8/pic/Task_5img.jpg" alt="Облачный хостинг" />
            </div>
            <div class="label1">
                Облачный хостинг
            </div>
            <div class="label2">
                68.95$ в месяц
            </div>
            <button>Подробнее</button>
        </div>
        <div class="column">
            <div class="pic3">
                <img src="~/css/Task_8/pic/Task_5img.jpg" alt="Выделенный сервер" />
            </div>
            <div class="label1">
                Выделенный сервер
            </div>
            <div class="label2">
                217.95$ в месяц
            </div>
            <button>Подробнее</button>
        </div>
    </div>
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_6.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Эквалайзер</title>
    <environment include="Development">
        <link href="~/css/Task_8/Task8_6Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div class="eq">
        <div class="first"></div>
        <div class="second"></div>
        <div class="third"></div>
        <div class="fourth"></div>
        <div class="fifth"></div>
        <div class="sixth"></div>
    </div>
    <div class="lines">
        <hr />
        <hr />
        <hr />
        <hr />
        <hr />
        <hr />
        <hr />
        <hr />
        <hr />
        <hr />
    </div>
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_7.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Слои</title>
    <environment include="Development">
        <link href="~/css/Task_8/Task8_7Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div class="firstblock">Анапест как композиционный анализ</div>
    <div class="secondblock">
        Рифма существенно осознаёт лирический дактиль, несмотря на отсутствие единого пунктуационного
        алгоритма. Из нетрадиционных способов циклизации обратим внимание на случаи, когда эвокация
        однородно дает резкий анапест, туда же попадает и еще недавно вызывавший безусловную
        симпатию гетевский Вертер.
    </div>
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_8.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ЭКГ-5А</title>
    <environment include="Development">
        <link href="~/css/Task_8/Task8_8Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div>
        <h1>ЭКГ-5</h1>
        <p>
            ЭКГ-5 — карьерный гусеничный экскаватор с ковшом вместимостью 5м<sup>3</sup> — электрическая карьерная полноповоротная лопата
            на гусеничном ходу, предназначенная для выемки и погрузки в транспортные средства полезных ископаемых и вскрышных пород,
            в том числе тяжёлых скальных, предварительно разрыхлённых взрывом, в угольной промышленности, а также для выполнения
            больших объёмов земляных работ в промышленном строительстве.
        </p>
    </div>
</body>
</html>

EPAM.Web.Basics/Views/Task_8/Task8_9.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Task8_9</title>
    <environment include="Development">
        <link href="~/css/Task_8/Task8_9Style.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div>
        <ul>
            <li><a href="#">Шаг 1</a></li>
            <li><a href="#">Шаг 2</a></li>
            <li><a href="#">Шаг 3</a></li>
            <li><a href="#">Шаг 4</a></li>
        </ul>
    </div>
</body>
</html>

EPAM.Web.Basics/Views/Task_9/Task9_1.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Char remover</title>
</head>
<body>
    <input id="Text1" type="text" value="У попа была собака" />
    <button id="btn">Remover</button>
    <script src="~/Script/Task_9/Task_9_1Script.js"></script>
</body>
</html>

EPAM.Web.Basics/Views/Task_9/Task9_2.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Task9_2</title>
</head>
<body>
    <input id="Text" type="text" value="3+4*2- 9/-11 =" />
    <button id="btn">Calculation</button>
    <script src="~/Script/Task_9/Task_9_2Script.js"></script>
</body>
</html>

EPAM.Web.Basics/Views/Task_9/Task9_3.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <environment include="Development">
        <link rel="stylesheet"  href="~/css/Task_9/Task9_3Style.css"/>
    </environment>
    <title>Task9_3</title>
</head>
<body>
    <div class="div1">
        <select id="slct1" name="slct1" class="selectControl-1" multiple="multiple" size="5">
        </select>
    </div>
    <div class="div2">
        <button id="btn1">></button>
        <br>
        <button id="btn2"><</button>
        <br>
        <button id="btnAll1">>></button>
        <br>
        <button id="btnAll2"><<</button>
    </div>
    <div class="div1">
        <select id="slct2" name="slct2" class="selectControl-1" multiple="multiple" size="5">
        </select>
    </div>
    <div class="div2">
        <button id="btn3">></button>
        <br>
        <button id="btn4"><</button>
        <br>
        <button id="btnAll3">>></button>
        <br>
        <button id="btnAll4"><<</button>
    </div>
    <div class="div1">
        <select id="slct3" name="slct3" class="selectControl-1" multiple="multiple" size="5">
        </select>
    </div>

    <script src="~/Script/Task_9/Task_9_3Script.js"></script>
</body>
</html>

EPAM.Web.Basics/Views/Task_9/Task9_4.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <environment include="Development">
        <link rel="stylesheet" href="~/css/Task_9/Task9_4Style.css" />
    </environment>
    <title>Task9_4</title>
</head>
<body>
    <div id="preloader">
        <div id="loader"></div>
    </div>
    <div id="timer">
        <h2 id="time"></h2>
        <button id="btn1"><</button>
        <button id="btn2">></button>
        <br>
        <button id="stop">◼</button>
        <button id="start">►</button>
    </div>
    <div id="pageNum">
        <p>Page 1</p>
    </div>
    <script src="~/Script/Task_9/Task_9_4Script.js"></script>
</body>
</html>

EPAM.Web.Basics/Views/Task_9/Task9_4_1.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <environment include="Development">
        <link rel="stylesheet" href="~/css/Task_9/Task9_4Style.css" />
    </environment>
    <title>Task9_4_1</title>
</head>
<body>
    <div id="preloader">
        <div id="loader"></div>
    </div>
    <div id="timer">
        <h2 id="time"></h2>
        <button id="btn1"><</button>
        <button id="btn2">></button>
        <br>
        <button id="stop">◼</button>
        <button id="start">►</button>
    </div>
    <div id="pageNum">
        <p>Page 2</p>
    </div>
    <script src="~/Script/Task_9/Task_9_4Script.js"></script>
</body>
</html>

EPAM.Web.Basics/Views/Task_9/Task9_4_2.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <environment include="Development">
        <link rel="stylesheet" href="~/css/Task_9/Task9_4Style.css" />
    </environment>
    <title>Task9_4_2</title>
</head>
<body>
    <div id="preloader">
        <div id="loader"></div>
    </div>
    <div id="timer">
        <h2 id="time"></h2>
        <button id="btn1"><</button>
        <a asp-controller="Task_9" asp-action="Task9_4">></a>
        <br>
        <button id="stop">◼</button>
        <button id="start">►</button>
    </div>
    <div id="pageNum">
        <p>Page 3</p>
    </div>
    <script src="~/Script/Task_9/Task_9_4_2Script.js"></script>
</body>
</html>